# ========================================
# CERTIFICATI ORDERER ORGANIZATION
# ========================================
OrdererOrgs:
  - Name: Orderer
    Domain: example.com
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer
        SANS:
          - localhost
          - 127.0.0.1

# ========================================
# CERTIFICATI PEER ORGANIZATIONS
# ========================================
PeerOrgs:
  # Organizzazione Proprietario Macchine
  - Name: Owner
    Domain: owner.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
      SANS:
        - localhost
        - 127.0.0.1
    Users:
      Count: 1

  # Organizzazione Manutenzione Ordinaria
  - Name: Ordinary
    Domain: ordinary.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
      SANS:
        - localhost
        - 127.0.0.1
    Users:
      Count: 1

  # Organizzazione Manutenzione Straordinaria
  - Name: Extraordinary
    Domain: extraordinary.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
      SANS:
        - localhost
        - 127.0.0.1
    Users:
      Count: 1